# Provider network interface, e.g. eth3
# general (eduncey)
ISP_INTERFACE="eth3"

# Startup arguments
NFQWS_BASE_ARGS="--lua-init=@/opt/etc/nfqws2/lua/zapret-lib.lua \
                 --lua-init=@/opt/etc/nfqws2/lua/zapret-antidpi.lua \
                 --lua-init=@/opt/etc/nfqws2/lua/zapret-auto.lua \
                 --blob=quic_initial:@/opt/etc/nfqws2/blobs/quic_initial.bin \
                 --blob=tls_clienthello:@/opt/etc/nfqws2/blobs/tls_clienthello.bin \
                 --blob=quic_dbankcloud:@/opt/etc/nfqws2/blobs/quic_initial_dbankcloud_ru.bin"

# HTTP(S) strategy
NFQWS_ARGS="--filter-tcp=443,80,1984,2053,2083,2087,2096,5222,8443 --filter-l7=http,tls,mtproto \
            --payload=tls_client_hello,mtproto_initial \
            --lua-desync=circular:fails=2:time=300:retrans=3:nld=2 \
            # Strategy 1
            --lua-desync=fake:blob=tls_clienthello:tls_mod=rnd,dupsid,sni=fonts.google.com:tcp_seq=10000:strategy=1 \
            --lua-desync=multisplit:pos=1,midsld:seqovl=1:seqovl_pattern=tls_clienthello:tcp_ts_up:strategy=1 \
            # Strategy 2
            --lua-desync=fake:blob=0x00000000:tcp_ack=-66000:tls_mod=rnd,dupsid,sni=www.google.com:repeats=2:strategy=2 \
            --lua-desync=multisplit:pos=1,midsld:strategy=2 \
            # Strategy 3
            --lua-desync=hostfakesplit:host=ozon.ru:midhost=host-2:seqovl=sniext+3:seqovl_pattern=tls_clienthello:badsum:tcp_md5:tcp_ts_up:strategy=3 \
            --lua-desync=hostfakesplit:tcp_md5:tcp_ts_up:strategy=3 \
	    # Strategy 4
	    --lua-desync=fake:blob=tls_clienthello:tls_mod=rnd,dupsid,sni=www.google.com:strategy=4 \
	    --lua-desync=hostfakesplit:host=www.google.com:altorder=1:fool=ts:strategy=4 \
            # HTTP
            --payload=http_req \
            --lua-desync=http_methodeol:badsum"

# QUIC strategy
NFQWS_ARGS_QUIC="--filter-udp=443 --filter-l7=quic \
                 --payload=quic_initial \
                 --lua-desync=fake:blob=quic_initial:repeats=11"

# UDP strategy
NFQWS_ARGS_UDP="--filter-udp=590-600,1400,5349,49152-49999,50101-65535 \
                --filter-l7=wireguard,mtproto,unknown \
                --out-range=<n2 \
                --payload=wireguard_initiation,wireguard_response,wireguard_cookie,mtproto_initial,unknown \
                --lua-desync=circular:fails=2:time=300:retrans=3:nld=2 \
                 # Strategy 1
                --lua-desync=fake:repeats=6:strategy=1 \
                 # Strategy 2
                --lua-desync=fake:blob=quic_initial:repeats=6:strategy=2"

# Working modes
MODE_LIST="--hostlist=/opt/etc/nfqws2/lists/user.list"
#MODE_ALL="--hostlist-exclude=/opt/etc/nfqws2/lists/exclude.list"
#MODE_AUTO="$MODE_LIST --hostlist-auto=/opt/etc/nfqws2/lists/auto.list --hostlist-auto-debug=/opt/var/log/nfqws2.log $MODE_ALL"
NFQWS_EXTRA_ARGS="$MODE_LIST"

# IP-lists
NFQWS_ARGS_IPSET="--ipset=/opt/etc/nfqws2/lists/ipset.list --ipset-exclude=/opt/etc/nfqws2/lists/ipset_exclude.list"

# Custom arguments
NFQWS_ARGS_CUSTOM="--filter-udp=3478-3481,19294-19344,50000-50100 --filter-l7=discord,stun --lua-desync=fake:blob=quic_dbankcloud:repeats=6 --new \
                   --filter-udp=3478-3481,19294-19344,50000-50100 --filter-l7=unknown --lua-desync=fake:blob=quic_dbankcloud:repeats=12:cutoff=n3"

# IPv6 support
IPV6_ENABLED=0

# TCP ports for iptables rules
TCP_PORTS=80,443,1984,2053,2083,2087,2096,5222,8443

# UDP ports for iptables rules
UDP_PORTS=443,590:600,1400,3478:3481,5349,19294:19344,50000:50100,49152:65535

# Keenetic policy name
POLICY_NAME="nfqws"
POLICY_EXCLUDE=0
LOG_LEVEL=0
LOG_DEBUG_PATH="@/opt/var/log/nfqws2-debug.log"
NFQUEUE_NUM=300
USER=nobody
CONFIG_VERSION=1
